"""Initial migration.

Revision ID: 41997b5d9165
Revises: 
Create Date: 2024-07-17 14:10:01.506078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41997b5d9165'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pref_starting_day', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pref_starting_day')

    # ### end Alembic commands ###
